# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from users.v1 import users_pb2 as users_dot_v1_dot_users__pb2


class UsersServiceStub(object):
    """UsersService — second proto package shipped by the starter.

    Lives in its own module so consumers see the multi-package layout:
    two top-level packages, each with their own buf.yaml module path
    under buf.yaml. Implementations ship in apps/service-a; the
    generated TS surface is re-exported from @repo/proto-gen.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/users.v1.UsersService/GetUser',
                request_serializer=users_dot_v1_dot_users__pb2.GetUserRequest.SerializeToString,
                response_deserializer=users_dot_v1_dot_users__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/users.v1.UsersService/CreateUser',
                request_serializer=users_dot_v1_dot_users__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=users_dot_v1_dot_users__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_stream(
                '/users.v1.UsersService/ListUsers',
                request_serializer=users_dot_v1_dot_users__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=users_dot_v1_dot_users__pb2.User.FromString,
                _registered_method=True)


class UsersServiceServicer(object):
    """UsersService — second proto package shipped by the starter.

    Lives in its own module so consumers see the multi-package layout:
    two top-level packages, each with their own buf.yaml module path
    under buf.yaml. Implementations ship in apps/service-a; the
    generated TS surface is re-exported from @repo/proto-gen.
    """

    def GetUser(self, request, context):
        """Fetch a single user by id. Returns NOT_FOUND when missing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Create a new user. Server assigns id and created_at.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Stream users matching an optional name prefix. Server flushes one
        message per row and ends the stream when the result set is drained.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=users_dot_v1_dot_users__pb2.GetUserRequest.FromString,
                    response_serializer=users_dot_v1_dot_users__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=users_dot_v1_dot_users__pb2.CreateUserRequest.FromString,
                    response_serializer=users_dot_v1_dot_users__pb2.CreateUserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=users_dot_v1_dot_users__pb2.ListUsersRequest.FromString,
                    response_serializer=users_dot_v1_dot_users__pb2.User.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users.v1.UsersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('users.v1.UsersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsersService(object):
    """UsersService — second proto package shipped by the starter.

    Lives in its own module so consumers see the multi-package layout:
    two top-level packages, each with their own buf.yaml module path
    under buf.yaml. Implementations ship in apps/service-a; the
    generated TS surface is re-exported from @repo/proto-gen.
    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UsersService/GetUser',
            users_dot_v1_dot_users__pb2.GetUserRequest.SerializeToString,
            users_dot_v1_dot_users__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UsersService/CreateUser',
            users_dot_v1_dot_users__pb2.CreateUserRequest.SerializeToString,
            users_dot_v1_dot_users__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/users.v1.UsersService/ListUsers',
            users_dot_v1_dot_users__pb2.ListUsersRequest.SerializeToString,
            users_dot_v1_dot_users__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
