# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users/v1/users.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'users/v1/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14users/v1/users.proto\x12\x08users.v1\"\x9c\x01\n\x04User\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12!\n\x0c\x64isplay_name\x18\x03 \x01(\tR\x0b\x64isplayName\x12,\n\x06status\x18\x04 \x01(\x0e\x32\x14.users.v1.UserStatusR\x06status\x12\x1d\n\ncreated_at\x18\x05 \x01(\tR\tcreatedAt\" \n\x0eGetUserRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"L\n\x11\x43reateUserRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12!\n\x0c\x64isplay_name\x18\x02 \x01(\tR\x0b\x64isplayName\"8\n\x12\x43reateUserResponse\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x0e.users.v1.UserR\x04user\"I\n\x10ListUsersRequest\x12\x1f\n\x0bname_prefix\x18\x01 \x01(\tR\nnamePrefix\x12\x14\n\x05limit\x18\x02 \x01(\rR\x05limit*\\\n\nUserStatus\x12\x1b\n\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n\x15USER_STATUS_SUSPENDED\x10\x02\x32\xc7\x01\n\x0cUsersService\x12\x33\n\x07GetUser\x12\x18.users.v1.GetUserRequest\x1a\x0e.users.v1.User\x12G\n\nCreateUser\x12\x1b.users.v1.CreateUserRequest\x1a\x1c.users.v1.CreateUserResponse\x12\x39\n\tListUsers\x12\x1a.users.v1.ListUsersRequest\x1a\x0e.users.v1.User0\x01\x42\xa7\x01\n\x0c\x63om.users.v1B\nUsersProtoP\x01ZJgithub.com/mateokadiu/grpc-monorepo-starter/clients/go/pb/users/v1;usersv1\xa2\x02\x03UXX\xaa\x02\x08Users.V1\xca\x02\x08Users\\V1\xe2\x02\x14Users\\V1\\GPBMetadata\xea\x02\tUsers::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users.v1.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.users.v1B\nUsersProtoP\001ZJgithub.com/mateokadiu/grpc-monorepo-starter/clients/go/pb/users/v1;usersv1\242\002\003UXX\252\002\010Users.V1\312\002\010Users\\V1\342\002\024Users\\V1\\GPBMetadata\352\002\tUsers::V1'
  _globals['_USERSTATUS']._serialized_start=438
  _globals['_USERSTATUS']._serialized_end=530
  _globals['_USER']._serialized_start=35
  _globals['_USER']._serialized_end=191
  _globals['_GETUSERREQUEST']._serialized_start=193
  _globals['_GETUSERREQUEST']._serialized_end=225
  _globals['_CREATEUSERREQUEST']._serialized_start=227
  _globals['_CREATEUSERREQUEST']._serialized_end=303
  _globals['_CREATEUSERRESPONSE']._serialized_start=305
  _globals['_CREATEUSERRESPONSE']._serialized_end=361
  _globals['_LISTUSERSREQUEST']._serialized_start=363
  _globals['_LISTUSERSREQUEST']._serialized_end=436
  _globals['_USERSSERVICE']._serialized_start=533
  _globals['_USERSSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
