// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: orders/v1/orders.proto

package ordersv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrdersService_CreateOrder_FullMethodName      = "/orders.v1.OrdersService/CreateOrder"
	OrdersService_GetOrder_FullMethodName         = "/orders.v1.OrdersService/GetOrder"
	OrdersService_ListOrders_FullMethodName       = "/orders.v1.OrdersService/ListOrders"
	OrdersService_BulkCreateOrders_FullMethodName = "/orders.v1.OrdersService/BulkCreateOrders"
	OrdersService_EchoOrders_FullMethodName       = "/orders.v1.OrdersService/EchoOrders"
)

// OrdersServiceClient is the client API for OrdersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrdersService — the reference service surface for the starter.
//
// Implementations live in apps/service-a; consumers in apps/service-b.
// Generators: ts-proto (TS/Nest), protoc-gen-go (Go), grpc_tools (Python).
type OrdersServiceClient interface {
	// Create a new order. Server assigns id and created_at.
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	// Fetch a single order by id. Returns NOT_FOUND when missing.
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error)
	// Stream orders matching the filter. Server flushes one per message
	// and ends the stream when the result set is exhausted.
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error)
	// Client-streaming import — client pushes any number of orders, the
	// server batches them and returns a single summary once the client
	// half-closes. Demonstrates the AsyncIterable input pattern.
	BulkCreateOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateOrderRequest, BulkCreateOrdersResponse], error)
	// Bidirectional — for every request the server emits exactly one
	// response, but in either direction the stream stays open as long as
	// the peer is writing. Useful for chat-style or RPC-pipelining tests.
	EchoOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateOrderRequest, Order], error)
}

type ordersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersServiceClient(cc grpc.ClientConnInterface) OrdersServiceClient {
	return &ordersServiceClient{cc}
}

func (c *ordersServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrdersService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, OrdersService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdersService_ServiceDesc.Streams[0], OrdersService_ListOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListOrdersRequest, Order]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_ListOrdersClient = grpc.ServerStreamingClient[Order]

func (c *ordersServiceClient) BulkCreateOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateOrderRequest, BulkCreateOrdersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdersService_ServiceDesc.Streams[1], OrdersService_BulkCreateOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateOrderRequest, BulkCreateOrdersResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_BulkCreateOrdersClient = grpc.ClientStreamingClient[CreateOrderRequest, BulkCreateOrdersResponse]

func (c *ordersServiceClient) EchoOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateOrderRequest, Order], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdersService_ServiceDesc.Streams[2], OrdersService_EchoOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateOrderRequest, Order]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_EchoOrdersClient = grpc.BidiStreamingClient[CreateOrderRequest, Order]

// OrdersServiceServer is the server API for OrdersService service.
// All implementations should embed UnimplementedOrdersServiceServer
// for forward compatibility.
//
// OrdersService — the reference service surface for the starter.
//
// Implementations live in apps/service-a; consumers in apps/service-b.
// Generators: ts-proto (TS/Nest), protoc-gen-go (Go), grpc_tools (Python).
type OrdersServiceServer interface {
	// Create a new order. Server assigns id and created_at.
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	// Fetch a single order by id. Returns NOT_FOUND when missing.
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	// Stream orders matching the filter. Server flushes one per message
	// and ends the stream when the result set is exhausted.
	ListOrders(*ListOrdersRequest, grpc.ServerStreamingServer[Order]) error
	// Client-streaming import — client pushes any number of orders, the
	// server batches them and returns a single summary once the client
	// half-closes. Demonstrates the AsyncIterable input pattern.
	BulkCreateOrders(grpc.ClientStreamingServer[CreateOrderRequest, BulkCreateOrdersResponse]) error
	// Bidirectional — for every request the server emits exactly one
	// response, but in either direction the stream stays open as long as
	// the peer is writing. Useful for chat-style or RPC-pipelining tests.
	EchoOrders(grpc.BidiStreamingServer[CreateOrderRequest, Order]) error
}

// UnimplementedOrdersServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdersServiceServer struct{}

func (UnimplementedOrdersServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrdersServiceServer) GetOrder(context.Context, *GetOrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrdersServiceServer) ListOrders(*ListOrdersRequest, grpc.ServerStreamingServer[Order]) error {
	return status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrdersServiceServer) BulkCreateOrders(grpc.ClientStreamingServer[CreateOrderRequest, BulkCreateOrdersResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BulkCreateOrders not implemented")
}
func (UnimplementedOrdersServiceServer) EchoOrders(grpc.BidiStreamingServer[CreateOrderRequest, Order]) error {
	return status.Errorf(codes.Unimplemented, "method EchoOrders not implemented")
}
func (UnimplementedOrdersServiceServer) testEmbeddedByValue() {}

// UnsafeOrdersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdersServiceServer will
// result in compilation errors.
type UnsafeOrdersServiceServer interface {
	mustEmbedUnimplementedOrdersServiceServer()
}

func RegisterOrdersServiceServer(s grpc.ServiceRegistrar, srv OrdersServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrdersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrdersService_ServiceDesc, srv)
}

func _OrdersService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_ListOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListOrdersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrdersServiceServer).ListOrders(m, &grpc.GenericServerStream[ListOrdersRequest, Order]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_ListOrdersServer = grpc.ServerStreamingServer[Order]

func _OrdersService_BulkCreateOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrdersServiceServer).BulkCreateOrders(&grpc.GenericServerStream[CreateOrderRequest, BulkCreateOrdersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_BulkCreateOrdersServer = grpc.ClientStreamingServer[CreateOrderRequest, BulkCreateOrdersResponse]

func _OrdersService_EchoOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrdersServiceServer).EchoOrders(&grpc.GenericServerStream[CreateOrderRequest, Order]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_EchoOrdersServer = grpc.BidiStreamingServer[CreateOrderRequest, Order]

// OrdersService_ServiceDesc is the grpc.ServiceDesc for OrdersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrdersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orders.v1.OrdersService",
	HandlerType: (*OrdersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrdersService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrdersService_GetOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListOrders",
			Handler:       _OrdersService_ListOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BulkCreateOrders",
			Handler:       _OrdersService_BulkCreateOrders_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "EchoOrders",
			Handler:       _OrdersService_EchoOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "orders/v1/orders.proto",
}
