// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: orders/v1/orders.proto

package ordersv1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderStatus — lifecycle of an order. Renumbering is a breaking change;
// buf breaking guards this in CI.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2
	OrderStatus_ORDER_STATUS_SHIPPED     OrderStatus = 3
	OrderStatus_ORDER_STATUS_DELIVERED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_SHIPPED",
		4: "ORDER_STATUS_DELIVERED",
		5: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PAID":        2,
		"ORDER_STATUS_SHIPPED":     3,
		"ORDER_STATUS_DELIVERED":   4,
		"ORDER_STATUS_CANCELLED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_v1_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_orders_v1_orders_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// LineItem — one SKU on an order.
type LineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku            string `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity       uint32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents uint64 `protobuf:"varint,4,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
}

func (x *LineItem) Reset()         { *x = LineItem{} }
func (x *LineItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (*LineItem) ProtoMessage()    {}

func (x *LineItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *LineItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LineItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *LineItem) GetUnitPriceCents() uint64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

// Order — the canonical order entity. Money is integer cents; times are
// ISO-8601 UTC strings (RFC 3339).
type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string      `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	LineItems  []*LineItem `protobuf:"bytes,3,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	TotalCents uint64      `protobuf:"varint,4,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Currency   string      `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status     OrderStatus `protobuf:"varint,6,opt,name=status,proto3,enum=orders.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt  string      `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Order) Reset()         { *x = Order{} }
func (x *Order) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Order) ProtoMessage()    {}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetLineItems() []*LineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *Order) GetTotalCents() uint64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string      `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	LineItems  []*LineItem `protobuf:"bytes,2,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	Currency   string      `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *CreateOrderRequest) Reset()         { *x = CreateOrderRequest{} }
func (x *CreateOrderRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateOrderRequest) ProtoMessage()    {}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetLineItems() []*LineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *CreateOrderResponse) Reset()         { *x = CreateOrderResponse{} }
func (x *CreateOrderResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateOrderResponse) ProtoMessage()    {}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOrderRequest) Reset()         { *x = GetOrderRequest{} }
func (x *GetOrderRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetOrderRequest) ProtoMessage()    {}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Limit      uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListOrdersRequest) Reset()         { *x = ListOrdersRequest{} }
func (x *ListOrdersRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListOrdersRequest) ProtoMessage()    {}

func (x *ListOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListOrdersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_orders_v1_orders_proto protoreflect.FileDescriptor

var (
	file_orders_v1_orders_proto_enumTypes  = make([]protoimpl.EnumInfo, 1)
	file_orders_v1_orders_proto_msgTypes   = make([]protoimpl.MessageInfo, 6)
	file_orders_v1_orders_proto_goTypes    = []interface{}{
		(OrderStatus)(0),
		(*LineItem)(nil),
		(*Order)(nil),
		(*CreateOrderRequest)(nil),
		(*CreateOrderResponse)(nil),
		(*GetOrderRequest)(nil),
		(*ListOrdersRequest)(nil),
	}
	file_orders_v1_orders_proto_depIdxs = []int32{}
)

var file_orders_v1_orders_proto_init_once sync.Once

func file_orders_v1_orders_proto_init() {
	file_orders_v1_orders_proto_init_once.Do(func() {
		// Real generated code registers descriptors here. This vendored stub
		// keeps the public API surface; run `buf generate` to produce the
		// full descriptor table.
		_ = reflect.TypeOf((*OrderStatus)(nil))
	})
}
