/**
 * @repo/connect-web — browser-friendly bindings for the same `.proto` files
 * the Node/Nest services consume. Generated by `buf generate` via
 * `@bufbuild/protoc-gen-es` (target=ts) into `src/gen/`.
 *
 * Pair with `@connectrpc/connect-web` to call services over the Connect
 * protocol (HTTP/JSON) or gRPC-Web (Protobuf-over-HTTP) from any browser.
 *
 *     import { createConnectTransport } from '@connectrpc/connect-web';
 *     import { createClient } from '@connectrpc/connect';
 *     import { OrdersService } from '@repo/connect-web/orders/v1';
 *
 *     const transport = createConnectTransport({ baseUrl: 'http://localhost:8080' });
 *     const client = createClient(OrdersService, transport);
 *     const { order } = await client.getOrder({ id: 'ord_x' });
 */
export * from './gen/orders/v1/orders_pb.js';
export * from './gen/users/v1/users_pb.js';
export * from './gen/grpc/health/v1/health_pb.js';
