# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: orders/v1/orders.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

# Stub: the full FileDescriptorProto serialised bytes belong here. Run
# `buf generate` to regenerate the real file. The wrapper module below
# provides import-compatible classes so application code resolves.

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders.v1.orders_pb2', _globals)


class OrderStatus:
    ORDER_STATUS_UNSPECIFIED = 0
    ORDER_STATUS_PENDING = 1
    ORDER_STATUS_PAID = 2
    ORDER_STATUS_SHIPPED = 3
    ORDER_STATUS_DELIVERED = 4
    ORDER_STATUS_CANCELLED = 5


class LineItem:
    """Stub message. Regenerate via `buf generate` to get the real protobuf class."""

    def __init__(self, sku: str = "", name: str = "", quantity: int = 0, unit_price_cents: int = 0):
        self.sku = sku
        self.name = name
        self.quantity = quantity
        self.unit_price_cents = unit_price_cents


class Order:
    def __init__(
        self,
        id: str = "",
        customer_id: str = "",
        line_items=None,
        total_cents: int = 0,
        currency: str = "",
        status: int = 0,
        created_at: str = "",
    ):
        self.id = id
        self.customer_id = customer_id
        self.line_items = line_items or []
        self.total_cents = total_cents
        self.currency = currency
        self.status = status
        self.created_at = created_at


class CreateOrderRequest:
    def __init__(self, customer_id: str = "", line_items=None, currency: str = ""):
        self.customer_id = customer_id
        self.line_items = line_items or []
        self.currency = currency


class CreateOrderResponse:
    def __init__(self, order: "Order | None" = None):
        self.order = order


class GetOrderRequest:
    def __init__(self, id: str = ""):
        self.id = id


class ListOrdersRequest:
    def __init__(self, customer_id: str = "", limit: int = 0):
        self.customer_id = customer_id
        self.limit = limit
