# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from orders.v1 import orders_pb2 as orders_dot_v1_dot_orders__pb2


class OrdersServiceStub:
    """OrdersService — the reference service surface for the starter."""

    def __init__(self, channel):
        self.CreateOrder = channel.unary_unary(
            '/orders.v1.OrdersService/CreateOrder',
            request_serializer=orders_dot_v1_dot_orders__pb2.CreateOrderRequest.SerializeToString
            if hasattr(orders_dot_v1_dot_orders__pb2.CreateOrderRequest, "SerializeToString")
            else (lambda m: b""),
            response_deserializer=orders_dot_v1_dot_orders__pb2.CreateOrderResponse.FromString
            if hasattr(orders_dot_v1_dot_orders__pb2.CreateOrderResponse, "FromString")
            else (lambda b: orders_dot_v1_dot_orders__pb2.CreateOrderResponse()),
        )
        self.GetOrder = channel.unary_unary(
            '/orders.v1.OrdersService/GetOrder',
            request_serializer=orders_dot_v1_dot_orders__pb2.GetOrderRequest.SerializeToString
            if hasattr(orders_dot_v1_dot_orders__pb2.GetOrderRequest, "SerializeToString")
            else (lambda m: b""),
            response_deserializer=orders_dot_v1_dot_orders__pb2.Order.FromString
            if hasattr(orders_dot_v1_dot_orders__pb2.Order, "FromString")
            else (lambda b: orders_dot_v1_dot_orders__pb2.Order()),
        )
        self.ListOrders = channel.unary_stream(
            '/orders.v1.OrdersService/ListOrders',
            request_serializer=orders_dot_v1_dot_orders__pb2.ListOrdersRequest.SerializeToString
            if hasattr(orders_dot_v1_dot_orders__pb2.ListOrdersRequest, "SerializeToString")
            else (lambda m: b""),
            response_deserializer=orders_dot_v1_dot_orders__pb2.Order.FromString
            if hasattr(orders_dot_v1_dot_orders__pb2.Order, "FromString")
            else (lambda b: orders_dot_v1_dot_orders__pb2.Order()),
        )


class OrdersServiceServicer:
    """Server-side API. Subclass and override the three methods."""

    def CreateOrder(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrders(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrdersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateOrder': grpc.unary_unary_rpc_method_handler(servicer.CreateOrder),
        'GetOrder': grpc.unary_unary_rpc_method_handler(servicer.GetOrder),
        'ListOrders': grpc.unary_stream_rpc_method_handler(servicer.ListOrders),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'orders.v1.OrdersService', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
